name: Build Base images
on:
  repository_dispatch:
    types: [package-updates]
  push:
    branches:
      - master
    paths:
      - "base/**"
      - ".github/workflows/base.yaml"

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish the base docker image
        run: bash .github/workflows/scripts/build-push.sh base base/Dockerfile
      - name: Build and publish the developer docker image
        run: bash .github/workflows/scripts/build-push.sh base-devel base/devel/Dockerfile

#      - name: Release images
#        uses: stefanzweifel/git-auto-commit-action@v4.15.3
#        if: success()
#        with:
#          commit_message: Update base image version
#
#      - name: Trigger update
#        if: success()
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          event-type: update-image-base
