name: Build base image
on:
  repository_dispatch:
    types: [package-updates]
  push:
    branches:
      - master
    paths:
      - "base/*"
      - "build-trigger"
      - ".github/workflows/base.yaml"

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish the Docker image
        run: |
          RELEASE_VERSION="$(date +%Y%m%d)-${GITHUB_RUN_NUMBER}"
          DOCKER_REPO="$(echo "docker.pkg.github.com/${GITHUB_REPOSITORY}/base" | tr '[:upper:]' '[:lower:]')"
          DOCKER_TAG_RELEASE="${DOCKER_REPO}:${RELEASE_VERSION}"
          DOCKER_TAG_LATEST="${DOCKER_REPO}:latest"
          echo "build ${DOCKER_TAG_RELEASE}"

          docker build --pull --file base/Dockerfile --tag "${DOCKER_TAG_RELEASE}" --tag "${DOCKER_TAG_LATEST}" base/
          docker push "${DOCKER_TAG_RELEASE}"
          docker push "${DOCKER_TAG_LATEST}"

          SEARCH="$(echo $DOCKER_REPO | sed 's#/#\\/#g')"
          find . -iname 'Dockerfile*' -exec perl -i -pe "s/${SEARCH}:(?\!latest).+$/${SEARCH}:${RELEASE_VERSION}/" {} \;

      - name: Release base image
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        if: success()
        with:
          commit_message: Update base image version

