name: Build Base images
on:
  repository_dispatch:
    types: [package-updates]

  pull_request:
    paths:
      - "base/**"

  push:
    branches:
      - master
    paths:
      - "base/**"
      - ".github/workflows/base.yaml"

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set version
        run: |
          echo "IMAGE_VERSION=$(date +%Y%m%d)-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
        env:
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}

      - name: Docker meta (base)
        id: meta-base
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/base
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}

      - name: Build and push (base)
        uses: docker/build-push-action@v5
        with:
          context: base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}

      - name: Docker meta (base-devel)
        id: meta-base-devel
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/base-devel
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}

      - name: Build and push (base-devel)
        uses: docker/build-push-action@v5
        with:
          context: base/devel
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base-devel.outputs.tags }}
          labels: ${{ steps.meta-base-devel.outputs.labels }}
