name: Build Base images
on:
  repository_dispatch:
    types: [package-updates]

  pull_request:
    branches:
      - master

  push:
    branches:
      - master
    paths:
      - "base/**"
      - ".github/workflows/base.yaml"

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set version
        run: |
          echo "IMAGE_VERSION=$(date +%Y%m%d)-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
        env:
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}

      - name: Docker meta (base)
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/base
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}

      - name: Build and push (base)
        uses: docker/build-push-action@v3
        with:
          context: base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Docker meta (base-devel)
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/base-devel
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}

      - name: Build and push (base-devel)
        uses: docker/build-push-action@v3
        with:
          context: base/devel
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: Release images
#        uses: stefanzweifel/git-auto-commit-action@v4.15.3
#        if: success()
#        with:
#          commit_message: Update base image version
#
#      - name: Trigger update
#        if: success()
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          event-type: update-image-base
