name: Build service image - Roundcube
on:
  repository_dispatch:
    types: [update-image-base]
  push:
    branches:
      - master
    paths:
      - "images/roundcube/**"
      - ".github/workflows/image-roundcube.yaml"

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker image
        run: bash .github/workflows/scripts/build-push.sh roundcube images/roundcube/Dockerfile