name: Build service image - CoreDNS
on:
  repository_dispatch:
    types: [update-image-base]

  pull_request:
    branches:
      - master
    paths:
      - "images/coredns/**"

  push:
    branches:
      - master
    paths:
      - "images/clamav/**"
      - ".github/workflows/image-coredns.yaml"
      - ".github/workflows/shared-build.yaml"

jobs:
  build:
    uses: ./.github/workflows/shared-build.yaml
    with:
      name: coredns
      path: images/coredns