name: Build service image - Roundcube
on:
  repository_dispatch:
    types: [update-image-base]

  pull_request:
    paths:
      - "images/roundcube/**"

  push:
    branches:
      - master
    paths:
      - "images/roundcube/**"
      - ".github/workflows/image-roundcube.yaml"
      - ".github/workflows/shared-build.yaml"

jobs:
  build:
    uses: ./.github/workflows/shared-build.yaml
    with:
      name: roundcube
      path: images/roundcube