name: Build service image - Exim
on:
  repository_dispatch:
    types: [update-image-base]

  pull_request:
    paths:
      - "images/exim/**"

  push:
    branches:
      - master
    paths:
      - "images/exim/**"
      - ".github/workflows/image-exim.yaml"
      - ".github/workflows/shared-build.yaml"

jobs:
  build:
    uses: ./.github/workflows/shared-build.yaml
    with:
      name: exim
      path: images/exim