name: Build service image - Clamav
on:
  repository_dispatch:
    types: [update-image-base]

  pull_request:
    paths:
      - "images/clamav/**"

  push:
    branches:
      - master
    paths:
      - "images/clamav/**"
      - ".github/workflows/image-clamav.yaml"
      - ".github/workflows/shared-build.yaml"

jobs:
  build:
    uses: ./.github/workflows/shared-build.yaml
    with:
      name: clamav
      path: images/clamav