name: Build service image - Restic
on:
  repository_dispatch:
    types: [update-image-base]

  pull_request:
    paths:
      - "images/restic/**"

  push:
    branches:
      - master
    paths:
      - "images/restic/**"
      - ".github/workflows/image-restic.yaml"
      - ".github/workflows/shared-build.yaml"

jobs:
  build:
    uses: ./.github/workflows/shared-build.yaml
    with:
      name: restic
      path: images/restic