name: Build service image - Exim
on:
  repository_dispatch:
    types: [update-image-base]
  push:
    branches:
      - master
    paths:
      - "images/exim/**"
      - ".github/workflows/image-exim.yaml"

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker image
        if: github.event_name != 'pull_request'
        run: bash .github/workflows/scripts/build-push.sh exim images/exim/Dockerfile