on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set version
        run: |
          echo "IMAGE_VERSION=$(date +%Y%m%d)-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ inputs.name }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.IMAGE_VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.path }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}