name: Check security updates
on:
  # Daily check
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write

jobs:

  check:
    name: Scheduled update check
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for security updates
        id: check_update
        run: bash .github/workflows/scripts/check-update.sh ghcr.io/project0/container-hub/base-devel:latest

      - name: Trigger update
        # exit code will be 100 if updates are available
        if: steps.check_update.outputs.update_result == '100'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: package-updates
