name: Check security updates
on:
  # Daily check
  schedule:
    - cron: '0 2 * * *'

jobs:

  check:
    name: Scheduled update check
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for security updates
        id: check_update
        run: bash .github/workflows/scripts/check-update.sh ghcr.io/project0/container-hub/base-devel:latest

      - name: Trigger update
        # exit code will be 100 if updates are available
        if: steps.check_update.outputs.update_result == '100'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: package-updates
