name: Check security updates
on:
  push:
    branches:
      - master
    paths:
      - "build-trigger-sec"

  # Daily check
  schedule:
    - cron: '0 2 * * *'

jobs:

  check:
    name: Scheduled update check
    # This job runs on Linux
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/project0/container-action-test/base:latest
    steps:
      - name: Check for updates
        run: |
          yum --security check-update
          echo "::set-output name=update_result::$?"

#    steps:
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          event-type: package-updates