name: Check security updates
on:

  # Daily check
  schedule:
    - cron: '0 2 * * *'

jobs:

  check:
    name: Scheduled update check
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # run check...

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: package-updates